// Dynamic image handler function
export const generateImageArray = (mainImage: string, productName: string) => {
  return [
    mainImage,
    mainImage, // We can add more views when available
    mainImage
  ];
};

// Fallback image generator
export const getImageWithFallback = (imageSrc: string, productName: string) => {
  return imageSrc || `https://via.placeholder.com/400x300/f3f4f6/6b7280?text=${encodeURIComponent(productName)}`;
};

export const products = [
  {
    id: 15,
    name: "Sport & Travel Backpack",
    category: "Bags",
    image: "/bag1.jpeg",
    images: generateImageArray("/bag1.jpeg", "Sport & Travel Backpack"),
    description: "Durable and stylish backpack perfect for sports, travel and daily use",
    detailedDescription: "This premium sport and travel backpack combines functionality with style. Made from high-quality water-resistant fabric, it features multiple compartments for organized storage. The ergonomic design ensures comfort during long hours of wear, making it perfect for students, professionals, and travelers.",
    specifications: {
      "Material": "Water-resistant polyester with reinforced stitching",
      "Capacity": "25-30 liters",
      "Compartments": "Main compartment, laptop sleeve, front pocket, side pockets",
      "Straps": "Padded adjustable shoulder straps",
      "Features": "Water bottle holder, headphone port, reflective strips",
      "Dimensions": "45cm x 30cm x 15cm"
    },
    tags: ["Travel", "Sports", "Durable"],
    animationType: "lift",
  },
  {
    id: 16,
    name: "Trendy Pink Backpack",
    category: "Bags",
    image: "/bag2.jpeg",
    images: generateImageArray("/bag2.jpeg", "Trendy Pink Backpack"),
    description: "Fashionable pink backpack with colorful patterns perfect for students and young professionals",
    detailedDescription: "Stand out with this eye-catching pink backpack featuring vibrant cartoon patterns and modern design elements. Made from premium materials, it offers both style and functionality. The spacious interior and multiple pockets make it ideal for school, college, or casual outings.",
    specifications: {
      "Material": "High-grade synthetic fabric with cartoon print",
      "Capacity": "20-25 liters",
      "Design": "Pink base with colorful character patterns",
      "Compartments": "Main compartment, front zip pocket, side mesh pockets",
      "Closure": "Double zipper with branded pulls",
      "Target Age": "Teens and young adults"
    },
    tags: ["Trendy", "Colorful", "Youth"],
    animationType: "pulse",
  },
  {
    id: 17,
    name: "Multi-Color Adventure Backpack",
    category: "Bags",
    image: "/bag3.jpeg",
    images: generateImageArray("/bag3.jpeg", "Multi-Color Adventure Backpack"),
    description: "Vibrant multi-colored backpack designed for outdoor adventures and daily activities",
    detailedDescription: "This striking multi-colored backpack features a unique color-block design that makes a bold statement. Built for versatility, it's perfect for hiking, camping, school, or everyday use. The robust construction and thoughtful design elements ensure it can handle whatever adventure comes your way.",
    specifications: {
      "Material": "Durable ripstop nylon with color-block design",
      "Capacity": "28-32 liters",
      "Colors": "Yellow, teal, orange, and black color combination",
      "Features": "Compression straps, external gear loops, rain cover",
      "Padding": "Padded back panel and shoulder straps",
      "Weight": "1.2kg (empty)"
    },
    tags: ["Adventure", "Colorful", "Outdoor"],
    animationType: "rotate",
  },
  {
    id: 18,
    name: "Military Style Tactical Backpack",
    category: "Bags",
    image: "/bag4.jpeg",
    images: generateImageArray("/bag4.jpeg", "Military Style Tactical Backpack"),
    description: "Rugged military-style backpack with camouflage pattern for outdoor enthusiasts",
    detailedDescription: "Built for the toughest conditions, this military-style tactical backpack features authentic camouflage patterns and military-grade construction. Perfect for outdoor activities, hiking, camping, or tactical training. The modular design allows for customization with additional pouches and accessories.",
    specifications: {
      "Material": "Heavy-duty canvas with camouflage print",
      "Capacity": "35-40 liters",
      "Pattern": "Woodland camouflage",
      "Features": "MOLLE webbing, hydration compatibility, chest and waist straps",
      "Durability": "Reinforced stress points, weather-resistant coating",
      "Use Cases": "Military, hiking, camping, tactical training"
    },
    tags: ["Military", "Tactical", "Heavy-duty"],
    animationType: "glow",
  },
  {
    id: 19,
    name: "Premium Table Linens",
    category: "Fabrics",
    image: "/table-linens.jpeg",
    images: generateImageArray("/table-linens.jpeg", "Premium Table Linens"),
    description: "Elegant purple table linens with intricate decorative patterns",
    detailedDescription: "Transform your dining experience with these premium table linens featuring beautiful purple fabric with sophisticated decorative patterns. Made from high-quality materials, these linens add elegance to any dining setting. Perfect for formal dinners, special occasions, or daily use.",
    specifications: {
      "Material": "Premium cotton blend with decorative weave",
      "Color": "Deep purple with intricate patterns",
      "Size Options": "Various sizes for different table dimensions",
      "Care Instructions": "Machine washable, gentle cycle recommended",
      "Finish": "Hemmed edges with decorative border",
      "Uses": "Dining tables, special occasions, home decor"
    },
    tags: ["Premium", "Decorative", "Elegant"],
    animationType: "pulse",
  },
  {
    id: 20,
    name: "Terry Cotton Towels",
    category: "Fabrics",
    image: "/terry-towels.jpeg",
    images: generateImageArray("/terry-towels.jpeg", "Terry Cotton Towels"),
    description: "Vibrant collection of soft terry cotton towels in multiple colors",
    detailedDescription: "Premium terry cotton towels available in a beautiful array of colors including teal, pink, purple, orange, and more. These towels are highly absorbent, quick-drying, and maintain their softness wash after wash. Perfect for bathrooms, kitchens, and spa use.",
    specifications: {
      "Material": "100% Terry cotton",
      "Weight": "500-600 GSM for superior absorbency",
      "Colors": "Multiple vibrant colors available",
      "Size Range": "Hand towels, bath towels, bath sheets",
      "Features": "Quick-dry, fade-resistant, antibacterial treatment",
      "Care": "Machine washable, tumble dry low"
    },
    tags: ["Absorbent", "Colorful", "Cotton"],
    animationType: "scale",
  },
  {
    id: 21,
    name: "Comfort Blankets",
    category: "Fabrics",
    image: "/blankets.jpeg",
    images: generateImageArray("/blankets.jpeg", "Comfort Blankets"),
    description: "Soft and cozy blankets in neutral tones for year-round comfort",
    detailedDescription: "Experience ultimate comfort with our premium blanket collection featuring soft, breathable fabrics in elegant neutral tones. These blankets provide perfect warmth without being too heavy, making them ideal for all seasons. The sophisticated cream and beige colors complement any home decor.",
    specifications: {
      "Material": "Blend of cotton and synthetic fibers",
      "Colors": "Cream, beige, and neutral tones",
      "Weight": "Medium weight for all-season use",
      "Size Options": "Twin, Queen, King sizes available",
      "Features": "Breathable, wrinkle-resistant, easy care",
      "Maintenance": "Machine washable, gentle cycle"
    },
    tags: ["Comfort", "Neutral", "All-season"],
    animationType: "lift",
  },
  {
    id: 22,
    name: "Zebra Pattern Bed Linens",
    category: "Fabrics",
    image: "/bed-linens-zebra.jpeg",
    images: generateImageArray("/bed-linens-zebra.jpeg", "Zebra Pattern Bed Linens"),
    description: "Modern zebra pattern bedding set for contemporary bedroom styling",
    detailedDescription: "Make a bold statement with this striking zebra pattern bedding set. The black and white design adds a modern, sophisticated touch to any bedroom. Made from quality fabric that's soft to the touch and durable enough for regular use. Perfect for those who love contemporary and animal print designs.",
    specifications: {
      "Pattern": "Black and white zebra stripe design",
      "Material": "High-quality cotton blend",
      "Set Includes": "Fitted sheet, flat sheet, pillowcases",
      "Thread Count": "200-250 TC for durability and comfort",
      "Size Options": "Single, Double, Queen, King",
      "Style": "Contemporary, animal print, modern"
    },
    tags: ["Modern", "Pattern", "Contemporary"],
    animationType: "rotate",
  },
  {
    id: 23,
    name: "Jacquard Bed Linens",
    category: "Fabrics",
    image: "/bed-linens-jacquard.jpeg",
    images: generateImageArray("/bed-linens-jacquard.jpeg", "Jacquard Bed Linens"),
    description: "Luxurious jacquard weave bed linens with intricate patterns",
    detailedDescription: "Indulge in luxury with these exquisite jacquard bed linens featuring intricate woven patterns. The sophisticated design and premium fabric quality create an elegant bedroom atmosphere. The jacquard weaving technique ensures durability while providing a rich, textured appearance.",
    specifications: {
      "Weave": "Jacquard with intricate patterns",
      "Material": "Premium cotton with jacquard weaving",
      "Color": "Elegant neutral tones with pattern details",
      "Thread Count": "300+ TC for luxury feel",
      "Set Includes": "Complete bedding set with decorative elements",
      "Care": "Professional cleaning recommended for longevity"
    },
    tags: ["Luxury", "Jacquard", "Premium"],
    animationType: "glow",
  },
  {
    id: 24,
    name: "Linens Collection Showcase",
    category: "Fabrics",
    image: "/linens-collection.jpeg",
    images: generateImageArray("/linens-collection.jpeg", "Linens Collection Showcase"),
    description: "Comprehensive collection of bed linens and table linens in various styles",
    detailedDescription: "Discover our complete linens collection featuring a variety of bed linens and table linens in different patterns and colors. This showcase represents our commitment to quality and variety, offering everything from classic white linens to decorative patterned pieces. Perfect for hotels, restaurants, or discerning homeowners.",
    specifications: {
      "Collection Type": "Mixed bed and table linens",
      "Variety": "Multiple patterns, colors, and styles",
      "Quality Grade": "Commercial and residential quality",
      "Material Range": "Cotton, cotton blends, premium fabrics",
      "Applications": "Hotels, restaurants, homes, events",
      "Customization": "Custom orders available"
    },
    tags: ["Collection", "Variety", "Commercial"],
    animationType: "flip",
  },
  {
    id: 25,
    name: "Premium Plain & Jacquard Bed Linens",
    category: "Fabrics",
    image: "/premium-bed-linens.jpeg",
    images: generateImageArray("/premium-bed-linens.jpeg", "Premium Plain & Jacquard Bed Linens"),
    description: "High-end bed linens combining plain and jacquard weave techniques",
    detailedDescription: "Experience the perfect blend of simplicity and sophistication with our premium bed linens that combine plain and jacquard weave techniques. These linens offer the best of both worlds - the elegant simplicity of plain weaves with the rich texture of jacquard patterns. Crafted from the finest materials for ultimate comfort and durability.",
    specifications: {
      "Technique": "Combination of plain and jacquard weaving",
      "Material": "Premium cotton with superior thread count",
      "Design": "Elegant patterns with plain sections",
      "Thread Count": "400+ TC for luxury comfort",
      "Color Palette": "Sophisticated neutral and metallic tones",
      "Durability": "Long-lasting with proper care"
    },
    tags: ["Premium", "Sophisticated", "Luxury"],
    animationType: "scale",
  },
  {
    id: 26,
    name: "Luxor Sandal Dhoop Sticks",
    category: "Dhoop",
    image: "/luxor-sandal-dhoop.jpeg",
    images: generateImageArray("/luxor-sandal-dhoop.jpeg", "Luxor Sandal Dhoop Sticks"),
    description: "Premium sandalwood dhoop sticks with long-lasting fragrance",
    detailedDescription: "Experience the divine aroma of authentic sandalwood with Luxor Sandal dhoop sticks. Made from premium quality sandalwood powder and natural aromatic herbs, these dhoop sticks provide a long-lasting, soothing fragrance perfect for meditation, prayers, and creating a peaceful atmosphere. Each stick burns evenly and fills your space with the classic, calming scent of sandalwood.",
    specifications: {
      "Fragrance": "Pure Sandalwood",
      "Burn Time": "45-60 minutes per stick",
      "Ingredients": "Sandalwood powder, natural aromatic herbs, binding agents",
      "Pack Size": "20-25 sticks per box",
      "Usage": "Meditation, prayers, aromatherapy, home ambiance",
      "Origin": "Traditional Indian incense making techniques"
    },
    tags: ["Sandalwood", "Premium", "Long-lasting"],
    animationType: "glow",
  },
  {
    id: 27,
    name: "Royally Premium Wet Dhoop",
    category: "Dhoop",
    image: "/royally-wet-dhoop.jpeg",
    images: generateImageArray("/royally-wet-dhoop.jpeg", "Royally Premium Wet Dhoop"),
    description: "Luxury wet dhoop with rich, intense fragrance for special occasions",
    detailedDescription: "Indulge in the royal experience with our premium wet dhoop, specially crafted for those who appreciate luxury and intensity in their spiritual practices. This wet dhoop offers a more concentrated and longer-lasting fragrance compared to traditional dry dhoop. Perfect for special pujas, festivals, and creating an atmosphere of grandeur and devotion.",
    specifications: {
      "Type": "Wet Dhoop (Concentrated)",
      "Fragrance Intensity": "High - Long-lasting rich aroma",
      "Burn Time": "60-90 minutes",
      "Application": "Special occasions, festivals, premium pujas",
      "Packaging": "Premium gift box packaging",
      "Features": "Smokeless burning, intense fragrance throw"
    },
    tags: ["Luxury", "Wet Dhoop", "Intense"],
    animationType: "pulse",
  },
  {
    id: 28,
    name: "Brindavan Nature's Gift Dhoop",
    category: "Dhoop",
    image: "/brindavan-dhoop.jpeg",
    images: generateImageArray("/brindavan-dhoop.jpeg", "Brindavan Nature's Gift Dhoop"),
    description: "Natural dhoop sticks made from pure herbs and traditional ingredients",
    detailedDescription: "Connect with nature through Brindavan's specially crafted dhoop sticks made from pure natural herbs and traditional ingredients. Inspired by the sacred gardens of Brindavan, these dhoop sticks bring the essence of nature into your spiritual practices. Made without artificial chemicals, they provide a pure, natural fragrance that enhances meditation and prayer experiences.",
    specifications: {
      "Ingredients": "Natural herbs, pure essential oils, organic binding agents",
      "Purity": "100% natural, no artificial chemicals",
      "Burn Time": "40-50 minutes per stick",
      "Fragrance Profile": "Herbal, floral, natural essence",
      "Environmental Impact": "Eco-friendly, biodegradable",
      "Spiritual Significance": "Inspired by sacred Brindavan gardens"
    },
    tags: ["Natural", "Herbal", "Eco-friendly"],
    animationType: "lift",
  },
  {
    id: 29,
    name: "Traditional Paisley Diyas Set",
    category: "Diyas",
    image: "/paisley-diyas.jpeg",
    images: generateImageArray("/paisley-diyas.jpeg", "Traditional Paisley Diyas Set"),
    description: "Elegant paisley-shaped decorative diyas in traditional red and green colors",
    detailedDescription: "Beautiful set of traditional paisley-shaped diyas crafted with intricate designs and vibrant colors. These decorative oil lamps feature the classic paisley motif in stunning red and green combinations with golden accents. Perfect for Diwali celebrations, pujas, and adding a traditional touch to your home decor. Each diya is carefully handcrafted and comes in an elegant gift box.",
    specifications: {
      "Design": "Traditional paisley shape with decorative patterns",
      "Colors": "Red and green with golden accents",
      "Set Size": "4 diyas per gift box",
      "Material": "High-quality ceramic with hand-painted details",
      "Occasion": "Diwali, festivals, religious ceremonies, home decor",
      "Packaging": "Premium gift box with protective padding"
    },
    tags: ["Traditional", "Paisley", "Festival"],
    animationType: "glow",
  },
  {
    id: 30,
    name: "Flower Candle Diyas Collection",
    category: "Diyas",
    image: "/flower-candle-diyas.jpeg",
    images: generateImageArray("/flower-candle-diyas.jpeg", "Flower Candle Diyas Collection"),
    description: "Beautiful flower-shaped diyas with colorful scented candles",
    detailedDescription: "Exquisite flower-shaped diyas featuring vibrant colored candles in pink and green. These decorative pieces combine the traditional beauty of diyas with the convenience of candles. Each piece is designed with intricate floral patterns and comes with premium quality scented candles. Perfect for creating a festive atmosphere during celebrations or for everyday home ambiance.",
    specifications: {
      "Design": "Flower-shaped with intricate petal patterns",
      "Candle Colors": "Pink and green scented candles included",
      "Set Size": "4 pieces per decorative box",
      "Material": "Decorative ceramic with metallic finish",
      "Features": "Scented candles, reusable diya holders",
      "Burn Time": "3-4 hours per candle"
    },
    tags: ["Floral", "Scented", "Decorative"],
    animationType: "pulse",
  },
  {
    id: 31,
    name: "Decorative Round Diyas with Borders",
    category: "Diyas",
    image: "/decorative-round-diyas.jpeg",
    images: generateImageArray("/decorative-round-diyas.jpeg", "Decorative Round Diyas with Borders"),
    description: "Classic round diyas with ornate decorative borders and white candles",
    detailedDescription: "Elegant round diyas featuring beautiful decorative borders with intricate patterns in multiple colors. These traditional-style oil lamps come with white candles and showcase classic Indian artistry with their colorful painted designs. The ornate borders add a royal touch, making them perfect for special occasions and religious ceremonies.",
    specifications: {
      "Shape": "Classic round with decorative border patterns",
      "Colors": "Multi-colored borders with white candles",
      "Set Size": "4 diyas per gift set",
      "Border Design": "Ornate traditional Indian patterns",
      "Material": "Premium ceramic with detailed hand-painting",
      "Usage": "Religious ceremonies, festivals, home decoration"
    },
    tags: ["Classic", "Ornate", "Traditional"],
    animationType: "scale",
  },
  {
    id: 32,
    name: "Colorful Flower Diyas Assortment",
    category: "Diyas",
    image: "/colorful-flower-diyas.jpeg",
    images: generateImageArray("/colorful-flower-diyas.jpeg", "Colorful Flower Diyas Assortment"),
    description: "Vibrant flower-shaped diyas in multiple bright colors - green, blue, and red",
    detailedDescription: "Stunning collection of flower-shaped diyas available in a beautiful array of colors including emerald green, royal blue, and deep red. Each diya features detailed petal designs and comes in an elegant presentation box. These colorful decorative pieces are perfect for creating a vibrant festive atmosphere and make excellent gifts for special occasions.",
    specifications: {
      "Design": "Detailed flower petals with geometric patterns",
      "Color Variety": "Green, blue, red, and mixed combinations",
      "Set Size": "6 diyas per luxury gift box",
      "Pattern": "Intricate floral and geometric designs",
      "Quality": "Premium ceramic with fade-resistant colors",
      "Gift Ready": "Luxury presentation box included"
    },
    tags: ["Colorful", "Luxury", "Gift Set"],
    animationType: "rotate",
  },
  {
    id: 33,
    name: "Leaf & Shell Shaped Diyas",
    category: "Diyas",
    image: "/leaf-shell-diyas.jpeg",
    images: generateImageArray("/leaf-shell-diyas.jpeg", "Leaf & Shell Shaped Diyas"),
    description: "Unique leaf and shell-shaped diyas with natural-inspired designs",
    detailedDescription: "Beautiful collection of nature-inspired diyas shaped like leaves and shells in various colors. These unique designs bring the beauty of nature into your spiritual practices and home decor. Each piece features detailed textures and patterns that mimic natural leaf veins and shell ridges, available in green, brown, and red color variations.",
    specifications: {
      "Shapes": "Leaf and shell inspired natural designs",
      "Colors": "Green, brown, red, and natural earth tones",
      "Set Size": "4 pieces per decorative gift box",
      "Texture": "Detailed natural patterns and textures",
      "Inspiration": "Nature-themed with organic flowing lines",
      "Versatility": "Suitable for both traditional and contemporary decor"
    },
    tags: ["Nature-inspired", "Unique", "Organic"],
    animationType: "flip",
  },
  {
    id: 34,
    name: "Complete Pooja Basket Set",
    category: "Pooja Samagri",
    image: "/pooja-basket-set.jpeg",
    images: generateImageArray("/pooja-basket-set.jpeg", "Complete Pooja Basket Set"),
    description: "Traditional wicker basket filled with essential pooja items and offerings",
    detailedDescription: "Complete pooja basket thoughtfully arranged with all essential items for Hindu worship and ceremonies. This traditional wicker basket includes diyas, fruits, sweets, incense, kumkum, rice, and other sacred offerings. Perfect for festivals, special pujas, or as a thoughtful gift for religious occasions. Each item is carefully selected to ensure authenticity and quality.",
    specifications: {
      "Basket Type": "Traditional handwoven wicker basket",
      "Contents": "Diyas, fruits, sweets, incense, kumkum, rice, sacred items",
      "Occasions": "Festivals, pujas, religious ceremonies, housewarming",
      "Authenticity": "Traditional items sourced from certified suppliers",
      "Gift Ready": "Beautifully arranged and ready for gifting",
      "Shelf Life": "Perishable items fresh, other items long-lasting"
    },
    tags: ["Complete Set", "Traditional", "Gift Ready"],
    animationType: "glow",
  },
  {
    id: 35,
    name: "Brass Puja Thali Set",
    category: "Pooja Samagri",
    image: "/brass-puja-thali.jpeg",
    images: generateImageArray("/brass-puja-thali.jpeg", "Brass Puja Thali Set"),
    description: "Premium brass worship plate with arranged pooja essentials and diyas",
    detailedDescription: "Elegant brass puja thali (worship plate) arranged with all essential items for daily prayers and special ceremonies. This premium quality brass plate includes multiple diyas, kumkum, rice, flowers, and sacred offerings arranged in traditional style. The brass construction ensures durability and adds a divine touch to your worship rituals.",
    specifications: {
      "Material": "Premium quality brass with golden finish",
      "Thali Size": "Medium to large diameter for complete arrangements",
      "Included Items": "Brass diyas, kumkum, rice, flowers, sacred offerings",
      "Usage": "Daily prayers, special pujas, aarti ceremonies",
      "Maintenance": "Easy to clean brass, long-lasting finish",
      "Design": "Traditional circular arrangement with compartments"
    },
    tags: ["Brass", "Premium", "Complete"],
    animationType: "pulse",
  },
  {
    id: 36,
    name: "Golden Deity Statues Set",
    category: "Pooja Samagri",
    image: "/golden-deity-statues.jpeg",
    images: generateImageArray("/golden-deity-statues.jpeg", "Golden Deity Statues Set"),
    description: "Exquisite golden figurines of Hindu deities for home temples and worship",
    detailedDescription: "Beautiful set of golden deity statues featuring intricately crafted figurines of Hindu gods and goddesses. These premium quality statues are perfect for home temples, office spaces, or as decorative pieces that bring divine blessings. Each statue is detailed with traditional iconography and finished in elegant golden tones.",
    specifications: {
      "Material": "High-quality metal with golden electroplating",
      "Deities": "Hindu gods and goddesses (Lakshmi, Ganesha, etc.)",
      "Finish": "Premium golden electroplated finish",
      "Craftsmanship": "Detailed traditional iconography and poses",
      "Size": "Medium size suitable for home temples",
      "Purpose": "Home temples, office decoration, divine blessings"
    },
    tags: ["Golden", "Deities", "Premium"],
    animationType: "scale",
  },
  {
    id: 37,
    name: "Traditional Rangoli Design Stencils",
    category: "Pooja Samagri",
    image: "/rangoli-designs.jpeg",
    images: generateImageArray("/rangoli-designs.jpeg", "Traditional Rangoli Design Stencils"),
    description: "Beautiful paisley and floral rangoli patterns for festival decorations",
    detailedDescription: "Create stunning floor art with these traditional rangoli design patterns featuring intricate paisley and floral motifs. Perfect for festivals like Diwali, Dussehra, and other special occasions. These reusable stencils help you create professional-looking rangoli designs with colored powders, flower petals, or rice.",
    specifications: {
      "Design Types": "Paisley patterns, floral motifs, traditional Indian designs",
      "Material": "Durable stencil material for multiple uses",
      "Festivals": "Diwali, Dussehra, Pongal, Onam, and other celebrations",
      "Usage": "Floor decoration, entrance beautification, courtyard art",
      "Compatibility": "Works with colored powders, petals, rice, sand",
      "Reusability": "Multiple uses with proper care and storage"
    },
    tags: ["Rangoli", "Traditional", "Festival"],
    animationType: "rotate",
  },
  {
    id: 38,
    name: "Sacred Religious Symbols Frame",
    category: "Pooja Samagri",
    image: "/religious-symbols-frame.jpeg",
    images: generateImageArray("/religious-symbols-frame.jpeg", "Sacred Religious Symbols Frame"),
    description: "Framed collection of traditional Hindu religious symbols and sacred geometry",
    detailedDescription: "Elegant framed artwork featuring traditional Hindu religious symbols and sacred geometric patterns. This beautiful piece combines various auspicious symbols including Om, Trishul, Swastika, and other sacred motifs in a sophisticated presentation. Perfect for home temples, living rooms, or offices to invoke divine blessings and positive energy.",
    specifications: {
      "Frame": "Premium quality frame with protective glass",
      "Symbols": "Om, Trishul, Swastika, and other sacred Hindu symbols",
      "Artwork": "Traditional designs with golden and colored accents",
      "Size": "Medium size suitable for wall mounting",
      "Purpose": "Home temples, wall decoration, spiritual ambiance",
      "Quality": "High-resolution artwork with fade-resistant colors"
    },
    tags: ["Sacred", "Framed", "Symbols"],
    animationType: "lift",
  },
  {
    id: 39,
    name: "Decorative Lotus Rangoli Set",
    category: "Pooja Samagri",
    image: "/decorative-lotus-rangoli.jpeg",
    images: generateImageArray("/decorative-lotus-rangoli.jpeg", "Decorative Lotus Rangoli Set"),
    description: "Colorful lotus-shaped rangoli pieces in pink and green for elegant decorations",
    detailedDescription: "Beautiful set of lotus-shaped decorative pieces perfect for creating stunning rangoli displays and floor decorations. Available in vibrant pink and green colors with intricate patterns, these reusable pieces can be arranged in various configurations to create elegant designs for festivals, ceremonies, and special occasions.",
    specifications: {
      "Design": "Lotus-shaped with detailed petal patterns",
      "Colors": "Vibrant pink and green with decorative elements",
      "Material": "Durable decorative material for multiple uses",
      "Set Contents": "Multiple lotus pieces in different sizes",
      "Arrangements": "Various configuration possibilities for different occasions",
      "Occasions": "Festivals, weddings, religious ceremonies, home decoration"
    },
    tags: ["Lotus", "Colorful", "Reusable"],
    animationType: "flip",
  },
  {
    id: 40,
    name: "Traditional Fiber Broom - Classic",
    category: "Broom",
    image: "/traditional-broom-1.jpeg",
    images: generateImageArray("/traditional-broom-1.jpeg", "Traditional Fiber Broom - Classic"),
    description: "Traditional Indian broom with natural fiber bristles and green handle",
    detailedDescription: "Authentic traditional Indian broom crafted with natural coconut fiber bristles and a sturdy green handle. This eco-friendly cleaning tool is perfect for both indoor and outdoor use. The natural fibers are excellent for sweeping all types of surfaces including concrete, wood, and tiles. The ergonomic green handle provides comfortable grip for extended use.",
    specifications: {
      "Bristle Material": "Natural coconut fiber",
      "Handle": "Green ergonomic handle for comfortable grip",
      "Length": "Standard broom length for effective cleaning",
      "Eco-Friendly": "100% biodegradable natural materials",
      "Usage": "Indoor and outdoor sweeping, all surface types",
      "Durability": "Long-lasting natural fibers with proper care"
    },
    tags: ["Traditional", "Eco-friendly", "Natural"],
    animationType: "lift",
  },
  {
    id: 41,
    name: "Premium Natural Fiber Broom",
    category: "Broom",
    image: "/traditional-broom-2.jpeg",
    images: generateImageArray("/traditional-broom-2.jpeg", "Premium Natural Fiber Broom"),
    description: "Premium quality natural fiber broom with enhanced durability and comfort",
    detailedDescription: "Premium grade traditional broom featuring high-quality natural coconut fiber bristles and an improved green handle design. This superior cleaning tool offers enhanced sweeping performance and longer durability. The carefully selected fibers provide excellent dust collection while the reinforced handle ensures comfortable use for extended cleaning sessions.",
    specifications: {
      "Quality Grade": "Premium quality natural coconut fiber",
      "Handle Design": "Enhanced green handle with improved grip",
      "Bristle Density": "High-density fiber arrangement for better cleaning",
      "Construction": "Reinforced binding for extended durability",
      "Performance": "Superior dust collection and surface cleaning",
      "Maintenance": "Easy to clean and maintain, long service life"
    },
    tags: ["Premium", "Durable", "Enhanced"],
    animationType: "scale",
  },
  {
    id: 42,
    name: "FlareonBBQ Coconut Shell Charcoal Briquette",
    category: "Barbecue",
    image: "/coconut-charcoal-briquette.jpeg",
    images: generateImageArray("/coconut-charcoal-briquette.jpeg", "FlareonBBQ Coconut Shell Charcoal Briquette"),
    description: "Premium coconut shell charcoal briquettes for superior grilling experience",
    detailedDescription: "FlareonBBQ premium coconut shell charcoal briquettes offer the ultimate grilling experience with longer burn time, consistent heat, and minimal ash production. Made from 100% natural coconut shells, these eco-friendly briquettes provide clean burning with no chemical additives. Perfect for barbecuing, grilling, and outdoor cooking with superior heat retention and flavor enhancement.",
    specifications: {
      "Material": "100% Natural coconut shell",
      "Burn Time": "3-4 hours consistent heat",
      "Heat Output": "High temperature with even distribution",
      "Ash Content": "Minimal ash production for easy cleanup",
      "Chemical Free": "No artificial binders or chemical additives",
      "Environmental": "Eco-friendly and sustainable fuel source"
    },
    tags: ["Premium", "Eco-friendly", "Long-burning"],
    animationType: "glow",
  },
  {
    id: 43,
    name: "Roundhouse Series BBQ Grill",
    category: "Barbecue",
    image: "/roundhouse-bbq-grill.jpeg",
    images: generateImageArray("/roundhouse-bbq-grill.jpeg", "Roundhouse Series BBQ Grill"),
    description: "Professional round BBQ grill with porcelain enamel bowl and temperature control",
    detailedDescription: "The Roundhouse Series BBQ grill features a professional-grade design with porcelain enamel cooking bowl and lid for superior heat retention and durability. Equipped with rust-resistant aluminum dampers, removable galvanized steel ash catcher, and stainless steel legs with all-weather wheels. The dome-style lid creates ideal air circulation for perfect smoking and grilling results.",
    specifications: {
      "Bowl & Lid": "Porcelain enamel for durability and heat retention",
      "Dampers": "Rust-resistant aluminum for temperature control",
      "Ash Catcher": "Removable galvanized steel for easy cleaning",
      "Legs": "Stainless steel with all-weather wheels for mobility",
      "Temperature Gauge": "Lid-mounted gauge for precise cooking control",
      "Handle": "Sturdy handle with aluminum heat shield"
    },
    tags: ["Professional", "Durable", "Mobile"],
    animationType: "pulse",
  },
  {
    id: 44,
    name: "Skipper Series Compact BBQ Grill",
    category: "Barbecue",
    image: "/skipper-bbq-grill.jpeg",
    images: generateImageArray("/skipper-bbq-grill.jpeg", "Skipper Series Compact BBQ Grill"),
    description: "Compact portable BBQ grill with foldable legs and chrome-plated cooking grid",
    detailedDescription: "The Skipper Series offers a perfect balance of portability and performance with its compact design and foldable legs for easy storage. Features a porcelain enamel cooking bowl, rust-resistant aluminum dampers for precise temperature control, and a chrome-plated cooking grid for excellent heat distribution. Ideal for small gatherings, camping, and limited outdoor spaces.",
    specifications: {
      "Design": "Compact and portable with space-saving features",
      "Legs": "Foldable legs for easy storage and transport",
      "Cooking Grid": "Chrome-plated for even heat distribution",
      "Bowl": "Porcelain enamel cooking bowl for durability",
      "Dampers": "Rust-resistant aluminum for temperature control",
      "Storage": "Convenient folding design for small spaces"
    },
    tags: ["Compact", "Portable", "Space-saving"],
    animationType: "scale",
  },
  {
    id: 45,
    name: "FlareonBBQ Premium Charcoal Collection",
    category: "Barbecue",
    image: "/premium-charcoal-boxes.jpeg",
    images: generateImageArray("/premium-charcoal-boxes.jpeg", "FlareonBBQ Premium Charcoal Collection"),
    description: "Premium charcoal collection in multiple sizes for all grilling needs",
    detailedDescription: "FlareonBBQ premium charcoal collection offers high-quality charcoal in various packaging sizes to suit different grilling requirements. Available in 5kg and 3kg boxes, this premium charcoal provides consistent heat, long burn time, and minimal smoke production. Perfect for both casual backyard grilling and professional cooking applications.",
    specifications: {
      "Package Sizes": "5kg and 3kg boxes available",
      "Charcoal Type": "Premium grade natural charcoal",
      "Burn Quality": "Consistent heat with minimal smoke",
      "Packaging": "Convenient boxes for easy storage and handling",
      "Applications": "Suitable for all types of grilling and barbecuing",
      "Quality": "Professional grade for consistent performance"
    },
    tags: ["Variety", "Professional", "Convenient"],
    animationType: "lift",
  },
  {
    id: 46,
    name: "Kali Cock Safety Matches Display Box",
    category: "Matchbox",
    image: "/kali-cock-safety-matches.jpeg",
    images: generateImageArray("/kali-cock-safety-matches.jpeg", "Kali Cock Safety Matches Display Box"),
    description: "Premium safety matches display box with iconic rooster branding",
    detailedDescription: "Kali Cock Safety Matches presented in a professional display box containing multiple matchboxes with the iconic colorful rooster branding. These premium quality safety matches are known for their reliability, consistent ignition, and long-lasting flame. The display box is perfect for retail purposes and bulk storage, featuring the traditional yellow design with the distinctive rooster logo that has been trusted for generations.",
    specifications: {
      "Brand": "Kali Cock - Traditional Indian match brand",
      "Type": "Safety matches with striker on box",
      "Display Box": "Clear protective display case for retail presentation",
      "Contents": "Multiple individual matchboxes per display unit",
      "Match Quality": "Premium wood sticks with reliable ignition tips",
      "Safety Features": "Strike-anywhere safety match design",
      "Packaging": "Traditional yellow boxes with iconic rooster branding"
    },
    tags: ["Safety Matches", "Display Box", "Traditional"],
    animationType: "glow",
  },
  {
    id: 47,
    name: "Eclair Simply Irresistible Toffees",
    category: "Confectionaries",
    image: "/eclair-toffee-jar.jpeg",
    images: generateImageArray("/eclair-toffee-jar.jpeg", "Eclair Simply Irresistible Toffees"),
    description: "Premium toffee candies in convenient storage jar with rich chocolate flavor",
    detailedDescription: "Eclair Simply Irresistible toffees offer a delightful chocolate experience in every bite. These premium quality toffees are individually wrapped and packed in a convenient storage jar, making them perfect for sharing or enjoying over time. Each toffee is crafted with rich chocolate flavor and a smooth, creamy texture that melts in your mouth, providing an irresistible treat for chocolate lovers of all ages.",
    specifications: {
      "Brand": "Eclair - Premium confectionery brand",
      "Flavor": "Rich chocolate with creamy toffee center",
      "Packaging": "Convenient storage jar with individual wrapped toffees",
      "Weight": "Multiple serving sizes available",
      "Ingredients": "High-quality chocolate, milk, sugar, and natural flavors",
      "Shelf Life": "Extended shelf life with proper storage",
      "Target": "All age groups, chocolate enthusiasts"
    },
    tags: ["Chocolate", "Toffee", "Premium"],
    animationType: "pulse",
  },
  {
    id: 48,
    name: "ChocD Eclair Chocolate Collection",
    category: "Confectionaries",
    image: "/chocd-eclair-collection.jpeg",
    images: generateImageArray("/chocd-eclair-collection.jpeg", "ChocD Eclair Chocolate Collection"),
    description: "Delicious chocolate candies available in multiple packaging options",
    detailedDescription: "ChocD Eclair offers a premium chocolate candy collection available in various convenient packaging options including jars and individual packets. These rich chocolate candies feature a perfect balance of sweetness and cocoa flavor, making them an ideal choice for gifting or personal enjoyment. Each piece is carefully crafted to deliver a consistent chocolate experience with every bite.",
    specifications: {
      "Brand": "ChocD Eclair - Chocolate specialists",
      "Variety": "Rich chocolate candies with smooth texture",
      "Packaging Options": "Storage jars and individual packets available",
      "Chocolate Type": "Premium milk chocolate with quality cocoa",
      "Usage": "Perfect for gifting, sharing, and personal consumption",
      "Quality": "Consistent taste and texture in every piece",
      "Storage": "Easy storage with resealable packaging options"
    },
    tags: ["Chocolate", "Variety Pack", "Gift"],
    animationType: "scale",
  },
  {
    id: 49,
    name: "Fruito Pop Colorful Lollipops",
    category: "Confectionaries",
    image: "/fruito-pop-lollipops.jpeg",
    images: generateImageArray("/fruito-pop-lollipops.jpeg", "Fruito Pop Colorful Lollipops"),
    description: "Fun fruit-flavored lollipops in attractive dispenser jar and individual packs",
    detailedDescription: "Fruito Pop brings joy with its colorful collection of fruit-flavored lollipops available in an attractive pink dispenser jar and convenient individual packets. These vibrant lollipops offer a variety of delicious fruit flavors that appeal to children and adults alike. The fun dispenser jar makes it easy to serve and display, while individual packets are perfect for on-the-go treats and party favors.",
    specifications: {
      "Brand": "Fruito Pop - Fun fruit candy specialists",
      "Flavors": "Multiple fruit flavors including strawberry, orange, and mixed fruits",
      "Packaging": "Attractive dispenser jar and individual packets",
      "Colors": "Vibrant multi-colored lollipops",
      "Target Audience": "Children and young adults",
      "Occasions": "Parties, celebrations, everyday treats",
      "Features": "Easy-grip sticks and long-lasting flavor"
    },
    tags: ["Lollipops", "Fruit Flavors", "Colorful"],
    animationType: "rotate",
  },
  {
    id: 50,
    name: "Farmers Harvest Jaggery Powder",
    category: "Jaggery",
    image: "/farmers-harvest-jaggery-powder.jpeg",
    images: generateImageArray("/farmers-harvest-jaggery-powder.jpeg", "Farmers Harvest Jaggery Powder"),
    description: "Premium organic jaggery powder made from fresh sugarcane juice",
    detailedDescription: "Farmers Harvest Jaggery Powder is a pure, natural sweetener made from fresh sugarcane juice using traditional methods. This golden-brown powder retains all the natural minerals and nutrients found in sugarcane, making it a healthier alternative to refined sugar. Rich in iron, calcium, and antioxidants, it provides sustained energy and offers numerous health benefits while adding a distinctive caramel-like flavor to your food and beverages.",
    specifications: {
      "Brand": "Farmers Harvest - Premium organic products",
      "Ingredient": "100% Pure sugarcane juice, no additives",
      "Processing": "Traditional boiling and grinding methods",
      "Nutrition": "Rich in iron, calcium, potassium, and antioxidants",
      "Texture": "Fine powder for easy mixing and dissolution",
      "Usage": "Cooking, baking, beverages, desserts",
      "Health Benefits": "Natural energy booster, aids digestion, rich in minerals"
    },
    tags: ["Organic", "Natural Sweetener", "Healthy"],
    animationType: "glow",
  },
  {
    id: 51,
    name: "MTR Ready Meals Collection - Paneer & Rice Varieties",
    category: "Masala Powder",
    image: "/mtr-ready-meals-set1.jpeg",
    images: generateImageArray("/mtr-ready-meals-set1.jpeg", "MTR Ready Meals Collection - Paneer & Rice Varieties"),
    description: "Premium ready-to-cook meals featuring Paneer Tikka Masala, Palak Paneer, Suji Halwa & Veg Pulao",
    detailedDescription: "MTR Ready Meals brings you authentic Indian flavors with this premium collection featuring four popular dishes: Paneer Tikka Masala, Palak Paneer, Suji Halwa, and Veg Pulao. Each packet contains carefully blended spices and ingredients that recreate traditional homestyle cooking in minutes. Made with high-quality ingredients and traditional recipes, these ready-to-cook meals offer convenience without compromising on taste.",
    specifications: {
      "Brand": "MTR - Trusted Indian food brand since 1924",
      "Varieties": "Paneer Tikka Masala, Palak Paneer, Suji Halwa, Veg Pulao",
      "Cooking Time": "5-10 minutes preparation time",
      "Ingredients": "Premium spices, dehydrated vegetables, natural flavors",
      "Serving Size": "2-3 servings per pack",
      "Shelf Life": "12-18 months from manufacturing date",
      "Preparation": "Just add water/milk and cook as per instructions"
    },
    tags: ["Ready-to-Cook", "Authentic", "Convenient"],
    animationType: "pulse",
  },
  {
    id: 52,
    name: "MTR Ready Meals Collection - Traditional Curries",
    category: "Masala Powder",
    image: "/mtr-ready-meals-set2.jpeg",
    images: generateImageArray("/mtr-ready-meals-set2.jpeg", "MTR Ready Meals Collection - Traditional Curries"),
    description: "Authentic Indian curry collection with Methi Matar, Paneer Makhani, Rajma Masala & Veg Biryani",
    detailedDescription: "Experience the rich flavors of traditional Indian curries with this MTR collection featuring Methi Matar, Paneer Makhani, Rajma Masala, and Veg Biryani. Each variety is crafted using time-tested recipes and premium quality ingredients. These ready-to-cook meals bring the authentic taste of homemade Indian food to your table with minimal effort and maximum flavor.",
    specifications: {
      "Brand": "MTR - Heritage Indian cuisine brand",
      "Varieties": "Methi Matar, Paneer Makhani, Rajma Masala, Veg Biryani",
      "Authenticity": "Traditional recipes with authentic spice blends",
      "Nutritional": "Rich in proteins, fiber, and essential nutrients",
      "Cooking Method": "Stovetop or microwave preparation options",
      "Packaging": "Vacuum-sealed pouches for freshness",
      "Usage": "Perfect for quick meals, office lunches, travel"
    },
    tags: ["Traditional", "Curry", "Premium"],
    animationType: "scale",
  },
  {
    id: 53,
    name: "MTR Ready Meals Collection - Dal & Chat Varieties",
    category: "Masala Powder",
    image: "/mtr-ready-meals-set3.jpeg",
    images: generateImageArray("/mtr-ready-meals-set3.jpeg", "MTR Ready Meals Collection - Dal & Chat Varieties"),
    description: "Wholesome collection featuring Aloo Chana Chat, Aloo Matar, Dal Palak & Dal Tadka",
    detailedDescription: "MTR's nutritious collection of dal and chat varieties offers a perfect blend of taste and health. This set includes Aloo Chana Chat, Aloo Matar, Dal Palak, and Dal Tadka - each packed with proteins, vitamins, and authentic Indian flavors. These ready-to-cook meals are ideal for those seeking wholesome, homestyle nutrition with the convenience of instant preparation.",
    specifications: {
      "Brand": "MTR - Quality assured since 1924",
      "Varieties": "Aloo Chana Chat, Aloo Matar, Dal Palak, Dal Tadka",
      "Nutritional Value": "High in protein, fiber, and essential vitamins",
      "Health Benefits": "Wholesome legumes and vegetables combination",
      "Cooking Style": "Traditional tempering and spice techniques",
      "Target": "Health-conscious consumers, busy professionals",
      "Preparation": "Ready in under 10 minutes"
    },
    tags: ["Healthy", "Dal Varieties", "Nutritious"],
    animationType: "lift",
  },
  {
    id: 54,
    name: "MTR Ready Meals Collection - Street Food & Comfort Foods",
    category: "Masala Powder",
    image: "/mtr-ready-meals-set4.jpeg",
    images: generateImageArray("/mtr-ready-meals-set4.jpeg", "MTR Ready Meals Collection - Street Food & Comfort Foods"),
    description: "Popular Indian comfort foods: Pau Bhaji, Punjabi Chole, Rice & Dal Tadka, Dal Makhani",
    detailedDescription: "Indulge in India's most beloved comfort foods with this MTR collection featuring Pau Bhaji, Punjabi Chole, Rice & Dal Tadka, and Dal Makhani. Each variety captures the essence of popular Indian street food and restaurant-style dishes. From the tangy Pau Bhaji to the creamy Dal Makhani, these ready-to-cook meals bring the authentic taste of Indian comfort food to your home kitchen.",
    specifications: {
      "Brand": "MTR - India's favorite ready meals brand",
      "Varieties": "Pau Bhaji, Punjabi Chole, Rice & Dal Tadka, Dal Makhani",
      "Flavor Profile": "Rich, creamy, and restaurant-style authentic taste",
      "Popular Appeal": "Street food and comfort food favorites",
      "Ingredients": "Premium spices, tomatoes, onions, dairy ingredients",  
      "Serving Suggestion": "Best served with rice, roti, or bread",
      "Occasion": "Perfect for weekend meals, entertaining guests"
    },
    tags: ["Comfort Food", "Street Food", "Restaurant Style"],
    animationType: "rotate",
  },
  {
    id: 55,
    name: "Medical & Educational Model Collection",
    category: "Lab Equipments",
    image: "/medical-educational-models.jpeg",
    images: generateImageArray("/medical-educational-models.jpeg", "Medical & Educational Model Collection"),
    description: "Comprehensive collection of medical and educational models for healthcare training",
    detailedDescription: "Professional-grade medical and educational model collection designed for healthcare institutions, medical colleges, and training centers. This comprehensive set includes dental models, nurse training manikin, ENT model, heart & lungs model, complete skeleton model, and life-size human vertebral column. Each model is anatomically accurate and made from durable materials for long-term educational use.",
    specifications: {
      "Collection Includes": "Dental models, Nurse training manikin, ENT model, Heart & lungs, Skeleton model, Vertebral column",
      "Material": "High-quality PVC, resin, and medical-grade plastics",
      "Accuracy": "Anatomically correct with detailed structures",
      "Target Users": "Medical colleges, nursing schools, healthcare training centers",
      "Durability": "Designed for repeated handling and demonstration",
      "Educational Value": "Comprehensive learning tools for medical education"
    },
    tags: ["Medical", "Educational", "Training"],
    animationType: "glow",
  },
  {
    id: 56,
    name: "Physics Laboratory Equipment Set",
    category: "Lab Equipments",
    image: "/physics-lab-equipment.jpeg",
    images: generateImageArray("/physics-lab-equipment.jpeg", "Physics Laboratory Equipment Set"),
    description: "Advanced physics laboratory equipment for experiments and demonstrations",
    detailedDescription: "Comprehensive physics laboratory equipment collection featuring precision instruments for advanced physics experiments. Includes Boyle's Law Apparatus, Michelson Interferometer, Two Beam Interference setup, Current and Voltage Sources, Radiation Counter, and Thermal & Electrical Conductivity apparatus. Perfect for undergraduate and graduate physics laboratories, research institutions, and advanced physics demonstrations.",
    specifications: {
      "Equipment Set": "Boyle's Law Apparatus, Michelson Interferometer, Two Beam Interference, Current & Voltage Sources, Radiation Counter, Thermal Conductivity apparatus",
      "Precision Level": "Research-grade accuracy and calibration",
      "Applications": "Thermodynamics, Optics, Electronics, Nuclear Physics experiments",
      "Target Users": "Universities, research labs, advanced physics education",
      "Quality": "Professional laboratory standard instruments",
      "Documentation": "Complete user manuals and experiment guides included"
    },
    tags: ["Physics", "Research", "Precision"],
    animationType: "pulse",
  },
  {
    id: 57,
    name: "Chemistry Laboratory Equipment Collection",
    category: "Lab Equipments",
    image: "/chemistry-lab-equipment.jpeg",
    images: generateImageArray("/chemistry-lab-equipment.jpeg", "Chemistry Laboratory Equipment Collection"),
    description: "Essential chemistry lab equipment including glassware and specialized apparatus",
    detailedDescription: "Complete chemistry laboratory equipment set featuring essential apparatus for analytical and organic chemistry experiments. The collection includes Hoffman Voltameter for electrolysis experiments, distillation apparatus for separation techniques, microfiltration assemblies for purification processes, and a comprehensive set of graduated beakers in various sizes. All equipment meets laboratory safety standards and is suitable for educational and research applications.",
    specifications: {
      "Equipment Includes": "Hoffman Voltameter, Distillation apparatus, Microfiltration assemblies, Graduated beakers set",
      "Glassware Quality": "Borosilicate glass with high thermal resistance",
      "Volume Range": "Multiple beaker sizes from 50ml to 1000ml",
      "Applications": "Electrolysis, distillation, filtration, general chemistry",
      "Safety Standards": "Laboratory-grade materials with safety certifications",
      "Educational Use": "Suitable for high school and college chemistry labs"
    },
    tags: ["Chemistry", "Glassware", "Essential"],
    animationType: "scale",
  },
]

// Helper function to get products by category
export const getProductsByCategory = (category: string) => {
  return products.filter(product => product.category === category);
};

// Helper function to get category mappings for homepage
export const getCategoryMappings = (): Record<string, typeof products> => {
  return {
    "Fabrics": getProductsByCategory("Fabrics"),
    "Dhoop": getProductsByCategory("Dhoop").concat(getProductsByCategory("Diyas"), getProductsByCategory("Pooja Samagri")),
    "Lab Equipments": getProductsByCategory("Lab Equipments")
  };
}; 